clone:
  git:
    image: hub.orion.home/woodpecker-cloner:1.0.11
    settings:
      skip_verify: true

pipeline:
  lint:
    image: hub.orion.home/dev-runtime:latest
    commands:
      - golangci-lint run
  test:
    image: hub.orion.home/dev-runtime:latest
    commands:
      - go test ./...
  build:
    image: hub.orion.home/docker:dind
    secrets: [hub_password]
    commands:
      - echo $HUB_PASSWORD | docker login --username oxhead --password-stdin hub.orion.home
      - docker build . -t hub.orion.home/casa:$CI_COMMIT_SHA
      - docker push hub.orion.home/casa:$CI_COMMIT_SHA
      - docker tag hub.orion.home/casa:$CI_COMMIT_SHA hub.orion.home/casa:latest
      - docker push hub.orion.home/casa:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
