clone:
  git:
    image: hub.orion.home/woodpecker-cloner:1.0.11
    settings:
      skip_verify: true

pipeline:
  lint:
    image: hub.orion.home/dev-runtime:latest
    commands:
      - golangci-lint run --timeout=5m

  test:
    image: hub.orion.home/dev-runtime:latest
    commands:
      - go test ./...

  build:
    image: hub.orion.home/dev-runtime:latest
    commands:
      - make

  docker:
    when:
      - event: tag
    image: hub.orion.home/docker:dind
    secrets: [hub_password]
    commands:
      - echo $HUB_PASSWORD | docker login --username oxhead --password-stdin hub.orion.home
      - docker build . -t hub.orion.home/casa:$CI_COMMIT_TAG
      - docker push hub.orion.home/casa:$CI_COMMIT_TAG
      - docker tag hub.orion.home/casa:$CI_COMMIT_TAG hub.orion.home/casa:latest
      - docker push hub.orion.home/casa:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
