// Code generated by qtc from "new_app.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/new_app.qtpl:1
package view

//line view/new_app.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/new_app.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/new_app.qtpl:1
func StreamNewApp(qw422016 *qt422016.Writer, csrfToken string) {
//line view/new_app.qtpl:1
	qw422016.N().S(`
  <div class="uk-flex uk-flex-column uk-flex-middle uk-margin-small-top">
    <div class="uk-card uk-card-default uk-card-body uk-width-1-2@m">
      <form action="/apps" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="csrf" value="`)
//line view/new_app.qtpl:5
	qw422016.E().S(csrfToken)
//line view/new_app.qtpl:5
	qw422016.N().S(`">
        <div class="uk-margin">
          <input type="text" class="uk-card-title uk-input" placeholder="Name of the app" name="title" autofocus>
        </div>
        <div class="uk-margin">
          <input type="text" class="uk-input" placeholder="Link to the app" name="url">
        </div>
        <div class="uk-margin">
          <textarea name="description" class="uk-input" placeholder="Describe what the app does"></textarea>
        </div>
        <div class="uk-margin" uk-margin>
          <div uk-form-custom="target: true" class="uk-flex uk-flex-row">
            <input type="file" name="image_file" aria-label="Custom controls">
            <input class="uk-input" type="text" placeholder="Select an icon file for the app" aria-label="Custom controls" disabled>
          </div>
        </div>
        <button class="uk-button uk-button-primary">Add</button>
      </form>
    </div>
  </div>
`)
//line view/new_app.qtpl:25
}

//line view/new_app.qtpl:25
func WriteNewApp(qq422016 qtio422016.Writer, csrfToken string) {
//line view/new_app.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/new_app.qtpl:25
	StreamNewApp(qw422016, csrfToken)
//line view/new_app.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line view/new_app.qtpl:25
}

//line view/new_app.qtpl:25
func NewApp(csrfToken string) string {
//line view/new_app.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line view/new_app.qtpl:25
	WriteNewApp(qb422016, csrfToken)
//line view/new_app.qtpl:25
	qs422016 := string(qb422016.B)
//line view/new_app.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line view/new_app.qtpl:25
	return qs422016
//line view/new_app.qtpl:25
}
